  - name: Deply a web application
    hosts: all
    tasks:
      - name: Install all required dependencies
        shell: apt-get install -y python python-setuptools python-dev build-essential python-pip python-mysqldb

      - name: Install MySQL
        shell: apt-get install -y mysql-server mysql-client