  - name: Deply a web application
    hosts: all
    tasks:
      - name: Install all required dependencies
        apt: name= {{ item }} state=installed
        with_items:
          - python
          - python-setuptools
          - pyhon-dev
          - build-essentials
          - python-pip

      - name: Install MySQL
        apt: name= {{ item }} state=installed
        with_items:
          - mysql-server
          - mysql-client

      - name: Start Web Server
        shell: cat /etc/hosts