  - name: Deply a web application
    hosts: all
    tasks:
      - name: Install all required dependencies
        action: apt pkg={{ items }} state=installed
        with_items:
          - python
          - python-setuptools
          - pyhon-dev
          - build-essentials
          - python-pip
          - elinks
