  - name: Deploy a web application
    hosts: all
    tasks:
      - name: Install all required dependencies
        action: >
          {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
        with_items:
          - python
          - python-setuptools
          - python-dev
          - build-essential
          - python-pip
          - python-mysqldb

      - include: tasks/deploy_db.yaml
      - include: tasks/deploy_web.yaml
