  - name: Deply a web application
    hosts: all
    tasks:
      - name: Install all required dependencies
        apt: name= {{ item }} state=latest
        with_items:
          - python
          - python-setuptools
          - pyhon-dev
          - build-essentials
          - python-pip
          - elinks