  - name: Deply a web application
    hosts: all
    tasks:
      - name: Install all required dependencies
        action: >
          {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
        with_items:
          - python
          - python-setuptools
          - python-dev
          - build-essential
          - python-pip
          - python-mysqldb
          - elinks
