  - name: Deply a web application
    hosts: web_and_db_servers
    tasks:
      - name: Install all required dependencies
        apt: name= {{ item }} state=installed
        with_items:
          - python
          - python-setuptools
          - pyhon-dev
          - build-essentials
          - python-pip

      - name: Install MySQL
        apt: name= {{ item }} state=installed
        with_items:
          - mysql-server
          - mysql-client